import SideBar from "@/components/SideBar";
import { Prociono } from "next/font/google";

const prociono = Prociono({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "Own Glovers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex lg:flex-row flex-col">
          <SideBar />
          <div className="ml-0 lg:ml-64 mt-24 lg:mt-0 w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
