import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/Provider";
import { ToastMessage } from "@/utils/Utility";
import "rsuite/dist/rsuite-no-reset.min.css";
import { CustomProvider } from "rsuite";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <CustomProvider>{children}</CustomProvider>
          <ToastMessage />
        </ReduxProvider>
      </body>
    </html>
  );
}
