import { Prociono } from "next/font/google";

const prociono = Prociono({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Own Glovers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={prociono.className}>{children}</body>
    </html>
  );
}
